[package]
name = "build-c"
version = "0.1.0"
edition = "2021"
default-run = "build-c"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[build-dependencies]
cc = "1.0.83"
